### ISSUE TITLE
Safari used as example but "Browser unsupported" for Local LLM

### ISSUE THREAD

**Issue by adavidzh** [poloclub/wordflow#1]
I just noticed that macOS Safari Version 17.3 (19617.2.4.11.8) reports Local LLM as "Browser unsupported" even if Safari is used as for the "Add to Dock..." in the project's ["Get Started"](https://github.com/poloclub/wordflow/blob/main/README.md#get-started):
<img width="1104" alt="image" src="https://github.com/poloclub/wordflow/assets/4256469/e71ecf2a-197f-4514-a674-9400dc3d98bc">

Since this sort of shortcut is also possible with Chrome, would it make sense to change the `README.md`?

**Comment by xiaohk** [comment]
Hi @adavidzh, good catch!! https://github.com/poloclub/wordflow/commit/fad861a3dd39cb16fb3630bc4c553e9b4b91b49d added a clarification about Safari and WebGPU in the README.

Yes, as you mentioned, Chrome users can also [create a Chrome app](https://support.google.com/chrome_webstore/answer/3060053?hl=en) and add it to the Dock :) I added it to the README. Thanks!
