### ISSUE TITLE
Missing Prompt Library in Local

### ISSUE THREAD

**Issue by z3rotto** [poloclub/wordflow#3]
Hi dear, 
I noticed the library from where to choose the prompts is missing when the script is installed in Local.
Do you have any ready library to add on?

**Comment by z3rotto** [comment]
Nope, I can use it and personalize prompts but I dont see any prompt in community section like the video and screenshoot show. 
Anyway, I love the app is fantastic! Please add more spaces to expand the number of favorite prompts available.

**Comment by z3rotto** [comment]
![Screenshot 2024-02-27 at 22-16-00 Wordflow](https://github.com/poloclub/wordflow/assets/141041044/ac29eafe-733d-45b5-8483-6d79aa4b1027)

**Comment by xiaohk** [comment]
Ah I see. Yes, this behavior is expected. For security response, requests to our backend are blocked by CORS if the domain is not `poloclub.github.io`. You can still run the LLM models by providing your own Google/OpenAI tokens though. Sorry for the inconvenience!

**Comment by z3rotto** [comment]
I love the concept by the way. Do you happen to have any json agents ready to share?

**Comment by xiaohk** [comment]
What do you mean by JSON agents?

**Comment by z3rotto** [comment]
I mean the file json of the instructions to give to GPT in ChatGPT Ultimate

**Comment by xiaohk** [comment]
I see. There might be some confusion. Wordflow is a standalone tool. It does not have JSON agents (used in GPT stores?). Wordflow just sends plain text prompts to LLM APIs (e.g., Gemini Pro and GPT 4). You can find the text prompts in the Community tab in the public version of Wordflow (https://poloclub.github.io/wordflow).
