### ISSUE TITLE
no ui. 

### ISSUE THREAD

**Issue by xvishon** [poloclub/wordflow#7]
Installed and launched wordflow. opened local URL in browser, Loads up a tab that says wordflow and has the icon in the tab but the page is a black white page with nothing displayed. Tried in Chrome and Opera.

**Comment by xiaohk** [comment]
Hi! I can successfully installed it with:

```bash
npm install
npm run dev
```

What error message do you see the in the browser's web console?

#### Shortcuts to open browser consoles

|OS|Browser|Shortcut|
|:---|:---|:---|
|macOS|Safari|Option + ⌘ + C|
|macOS|Chrome|Option + ⌘ + J| 
|macOS|Firefox|Option + ⌘ + K| 
|Windows|Edge|Ctrl + Shift + J| 
|Windows|Chrome|Ctrl + Shift + J| 
|Windows|Firefox|Ctrl + Shift + K|

**Comment by xvishon** [comment]
Well I'm not getting any error. Everything loads, I launch the URL in the browser and its a blank page with no UI. 
I get this in the source of the page that loads. but again its just a blank white page with no UI. 
`<html>
<body>

  | <!doctype html>
-- | --
  | <html lang="en">
  | <head>
  | <script type="module" src="/@vite/client"></script>
  |  
  | 
  | <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
  | <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
  | <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
  | <link rel="manifest" href="/site.webmanifest">
  | <meta name="msapplication-TileColor" content="#1e2327">
  | <meta name="theme-color" content="#1e2327">
  |  
  | <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  | <title>Wordflow</title>
  |  
  | 
  | <meta name="title" content="Wordflow" />
  | <meta
  | name="description"
  | content="Social and customizable AI writing assistant tool."
  | />
  |  
  | 
  | <meta property="og:type" content="website" />
  | <meta
  | property="og:url"
  | content="https://poloclub.github.io/wordflow/"
  | />
  | <meta property="og:title" content="Wordflow" />
  | <meta
  | property="og:description"
  | content="Social and customizable AI writing assistant tool."
  | />
  | <meta
  | property="og:image"
  | content="https://i.imgur.com/bjsHIZ6.png"
  | />
  |  
  | 
  | <meta property="twitter:card" content="summary_large_image" />
  | <meta
  | property="twitter:url"
  | content="https://poloclub.github.io/wordflow/"
  | />
  | <meta property="twitter:title" content="Wordflow" />
  | <meta
  | property="twitter:description"
  | content="Social and customizable AI writing assistant tool."
  | />
  | <meta
  | property="twitter:image"
  | content="https://i.imgur.com/bjsHIZ6.png"
  | />
  | <meta property="twitter:site" content="@jay4w" />
  | <meta property="twitter:creator" content="@jay4w" />
  |  
  | <link rel="preconnect" href="https://fonts.googleapis.com" />
  | <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  | <link
  | href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap"
  | rel="stylesheet"
  | />
  | <link
  | href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@100;200;300;400;500;600;700&display=swap"
  | rel="stylesheet"
  | />
  |  
  | 
  | <script async src="https://www.googletagmanager.com/gtag/js?id=G-RKCSR1T66F"></script>
  | <script>
  | window.dataLayer = window.dataLayer \|\| [];
  | function gtag(){dataLayer.push(arguments);}
  | gtag('js', new Date());
  |  
  | gtag('config', 'G-RKCSR1T66F');
  | </script>
  |  
  | <link rel="stylesheet" href="/global.css" />
  | <script type="module" src="/src/components/wordflow/wordflow.ts"></script>
  | </head>
  |  
  | <body>
  | <wordflow-wordflow> </wordflow-wordflow>
  | </body>
  | </html>


</body>
</html><!doctype html>
<html lang="en">
  <head>
    <script type="module" src="[/@vite/client](http://localhost:3000/@vite/client)"></script>

    <meta charset="UTF-8" />
    <link rel="apple-touch-icon" sizes="180x180" href="[/apple-touch-icon.png](http://localhost:3000/apple-touch-icon.png)">
    <link rel="icon" type="image/png" sizes="32x32" href="[/favicon-32x32.png](http://localhost:3000/favicon-32x32.png)">
    <link rel="icon" type="image/png" sizes="16x16" href="[/favicon-16x16.png](http://localhost:3000/favicon-16x16.png)">
    <link rel="manifest" href="[/site.webmanifest](http://localhost:3000/site.webmanifest)">
    <meta name="msapplication-TileColor" content="#1e2327">
    <meta name="theme-color" content="#1e2327">

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Wordflow</title>

    
    <meta name="title" content="Wordflow" />
    <meta
      name="description"
      content="Social and customizable AI writing assistant tool."
    />

    
    <meta property="og:type" content="website" />
    <meta
      property="og:url"
      content="https://poloclub.github.io/wordflow/"
    />
    <meta property="og:title" content="Wordflow" />
    <meta
      property="og:description"
      content="Social and customizable AI writing assistant tool."
    />
    <meta
      property="og:image"
      content="https://i.imgur.com/bjsHIZ6.png"
    />

    
    <meta property="twitter:card" content="summary_large_image" />
    <meta
      property="twitter:url"
      content="https://poloclub.github.io/wordflow/"
    />
    <meta property="twitter:title" content="Wordflow" />
    <meta
      property="twitter:description"
      content="Social and customizable AI writing assistant tool."
    />
    <meta
      property="twitter:image"
      content="https://i.imgur.com/bjsHIZ6.png"
    />
    <meta property="twitter:site" content="@jay4w" />
    <meta property="twitter:creator" content="@jay4w" />

    <link rel="preconnect" href="https://fonts.googleapis.com/" />
    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@100;200;300;400;500;600;700&display=swap"
      rel="stylesheet"
    />

    
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-RKCSR1T66F"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-RKCSR1T66F');
    </script>

    <link rel="stylesheet" href="[/global.css](http://localhost:3000/global.css)" />
    <script type="module" src="[/src/components/wordflow/wordflow.ts](http://localhost:3000/src/components/wordflow/wordflow.ts)"></script>
  </head>

  <body>
    <wordflow-wordflow> </wordflow-wordflow>
  </body>
</html>`

**Comment by xiaohk** [comment]
Do you see any messages in the web console? What's your chrome version?

**Comment by xvishon** [comment]
Chrome: Version 124.0.6367.208 (Official Build) (64-bit)
![image](https://github.com/poloclub/wordflow/assets/13268430/7fff4765-0463-4b74-9b65-a9561b2c82fc)

Thats all that is in the console. 

It seems like everything should be working.

![image](https://github.com/poloclub/wordflow/assets/13268430/537271f9-73b3-47ae-bd48-528cf215fd48)

That is all that loads when I access where the UI should be. 
There were no errors doing the npm install either.

**Comment by xiaohk** [comment]
Oh sorry, I meant the **browser**'s web console. You can open it with the following shortcuts in the browser:

|OS|Browser|Shortcut|
|:---|:---|:---|
|macOS|Safari|Option + ⌘ + C|
|macOS|Chrome|Option + ⌘ + J| 
|macOS|Firefox|Option + ⌘ + K| 
|Windows|Edge|Ctrl + Shift + J| 
|Windows|Chrome|Ctrl + Shift + J| 
|Windows|Firefox|Ctrl + Shift + K|

**Comment by xvishon** [comment]
Ahhh. ok there is this error. 
![image](https://github.com/poloclub/wordflow/assets/13268430/db48d0d0-b73b-41b0-988c-af65e0c91f5f)

**Comment by xiaohk** [comment]
Thanks. Oh I see. This issue should be fixed by d53e72ab16fe565409d84ca907a7232f1563e8ac. You can try to pull the latest code from main and re-install it.

**Comment by xvishon** [comment]
Ok that fixed it. I was pulling from the 0.1.7 for some reason.

**Comment by xvishon** [comment]
Side note: what are the chances of getting a custom end point for running a local model through openAI api so we can connect to oobabooga webUI?

**Comment by xiaohk** [comment]
Great!

Does this PR address your request? https://github.com/poloclub/wordflow/pull/5
